### ISSUE TITLE
Build and CI system integration

### ISSUE THREAD

**Issue by Eyedis390** [BME-MIT-IET/Dirty-Bits-iet-2019#1]
#### Software specifications
* GnuCash Android version: v2.4.0 
* System Android version: 27
* Gradle version: 4.1
* Java version: 1.8.0

**Comment by kisbusa007** [comment]
**Step 1.**
CI engedélyezése a projektre a https://travis-ci.org oldalon.
![image](https://user-images.githubusercontent.com/32656779/57192494-8a8ba900-6f31-11e9-9960-3329259175e4.png)

**Comment by kisbusa007** [comment]
**Step 2.**
A projekt eredetileg rendelkezik .travis.yml fájlal. Ami Travis CI rendszer szükséges beállításait tartalmazza. Így ezt nem kellett kézzel megírnunk.
Itt látható: https://github.com/BME-MIT-IET/Dirty-Bits-iet-2019/blob/working/.travis.yml

**Comment by kisbusa007** [comment]
Step 3.
A következő pushnál, már a https://travis-ci.org oldalon látható a build, és annak eredménye.
![image](https://user-images.githubusercontent.com/32656779/57192616-b3606e00-6f32-11e9-8f51-cac43b5f57bf.png)
