### ISSUE TITLE
SonarCube test

### ISSUE THREAD

**Issue by Eyedis390** [BME-MIT-IET/Dirty-Bits-iet-2019#2]
#### Software specifications
* GnuCash Android version: v2.4.0
* System Android version: 27
* sonarqube version: 7.7
* gradle version: 4.1 
* Java version:  1.8.0.

**Comment by kisbusa007** [comment]
**Step 1.**
A lokálisan elindítjuk a rendszerünknek megfelelő sonar verzót. 
![image](https://user-images.githubusercontent.com/32656779/57192744-0b4ba480-6f34-11e9-884b-9027357e2040.png)

**Comment by kisbusa007** [comment]
**Step 2.**
Ha a Sonarqube összes komponense sikeresen elindult, a http://localhost:9000/ címen elérhetjük a felületet.
![image](https://user-images.githubusercontent.com/32656779/57192777-654c6a00-6f34-11e9-9847-47da9cc2cee1.png)

**Comment by kisbusa007** [comment]
**Step 3.**
Hogy az andorid projektunk beépített gradle build rendszerével tudjuk használni a sonart, szerkesztenünk kell a build.gradle fájl.
A módosítások itt láthatók : https://github.com/BME-MIT-IET/Dirty-Bits-iet-2019/commit/b0ba051a0d368b67d341d2f38d3e073f3aa82a77

**Comment by kisbusa007** [comment]
**Step 4.** 
A beállítások elvégéze után, a projekt gyökérkönyvtárában kiadott `./gradlew sonarqube` parancs kiadásával inditható az elemzés. 
Az elemzés után pedig az eredmény már látható a sonarqube felületén:
![image](https://user-images.githubusercontent.com/32656779/57192896-e8ba8b00-6f35-11e9-8784-304b583bf31c.png)
